/* Daily lines for the weather display.
   One line shows per day: a quote on even days, a joke on odd days.
   The display shuffles each list once (the same way every time), so nothing repeats
   until a whole list has been shown. Add or remove lines freely. */

window.DAILY_QUOTES = [
  ["Well done is better than well said.", "Benjamin Franklin"],
  ["Lost time is never found again.", "Benjamin Franklin"],
  ["Diligence is the mother of good luck.", "Benjamin Franklin"],
  ["Hide not your talents, they for use were made. What's a sundial in the shade?", "Benjamin Franklin"],
  ["Early to bed and early to rise, makes a man healthy, wealthy, and wise.", "Benjamin Franklin"],
  ["An ounce of prevention is worth a pound of cure.", "Benjamin Franklin"],
  ["Little strokes fell great oaks.", "Benjamin Franklin"],
  ["He that can have patience can have what he will.", "Benjamin Franklin"],
  ["Haste makes waste.", "Benjamin Franklin"],
  ["Glass, china, and reputation are easily cracked, and never well mended.", "Benjamin Franklin"],
  ["There are no gains without pains.", "Benjamin Franklin"],
  ["Dost thou love life? Then do not squander time, for that's the stuff life is made of.", "Benjamin Franklin"],
  ["God helps them that help themselves.", "Benjamin Franklin, Poor Richard's Almanack"],
  ["Plough deep while sluggards sleep, and you shall have corn to sell and to keep.", "Benjamin Franklin"],
  ["The used key is always bright.", "Benjamin Franklin"],
  ["One today is worth two tomorrows.", "Benjamin Franklin"],
  ["Remember that time is money.", "Benjamin Franklin"],
  ["Either write things worth reading, or do things worth the writing.", "Benjamin Franklin"],
  ["Be at war with your vices, at peace with your neighbors, and let every new year find you a better man.", "Benjamin Franklin"],
  ["In this world nothing can be said to be certain, except death and taxes.", "Benjamin Franklin"],
  ["Wealth is not his that has it, but his that enjoys it.", "Benjamin Franklin"],
  ["Content makes poor men rich; discontent makes rich men poor.", "Benjamin Franklin"],
  ["Trust thyself: every heart vibrates to that iron string.", "Ralph Waldo Emerson"],
  ["Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson"],
  ["To be great is to be misunderstood.", "Ralph Waldo Emerson"],
  ["The only way to have a friend is to be one.", "Ralph Waldo Emerson"],
  ["Nothing can bring you peace but yourself.", "Ralph Waldo Emerson"],
  ["Write it on your heart that every day is the best day in the year.", "Ralph Waldo Emerson"],
  ["Finish every day and be done with it. You have done what you could.", "Ralph Waldo Emerson"],
  ["The creation of a thousand forests is in one acorn.", "Ralph Waldo Emerson"],
  ["The years teach much which the days never know.", "Ralph Waldo Emerson"],
  ["Every artist was first an amateur.", "Ralph Waldo Emerson"],
  ["Our life is frittered away by detail. Simplify, simplify.", "Henry David Thoreau"],
  ["If one advances confidently in the direction of his dreams, he will meet with a success unexpected in common hours.", "Henry David Thoreau"],
  ["If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them.", "Henry David Thoreau"],
  ["Rather than love, than money, than fame, give me truth.", "Henry David Thoreau"],
  ["I went to the woods because I wished to live deliberately.", "Henry David Thoreau"],
  ["Always bear in mind that your own resolution to succeed is more important than any other one thing.", "Abraham Lincoln"],
  ["With malice toward none, with charity for all.", "Abraham Lincoln"],
  ["Do what you can, with what you have, where you are.", "Theodore Roosevelt, quoting Bill Widener"],
  ["Far and away the best prize that life offers is the chance to work hard at work worth doing.", "Theodore Roosevelt"],
  ["The credit belongs to the man who is actually in the arena.", "Theodore Roosevelt"],
  ["Speak softly and carry a big stick; you will go far.", "Theodore Roosevelt, quoting a proverb"],
  ["The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"],
  ["Ask not what your country can do for you; ask what you can do for your country.", "John F. Kennedy"],
  ["The time to repair the roof is when the sun is shining.", "John F. Kennedy"],
  ["We choose to go to the moon... not because they are easy, but because they are hard.", "John F. Kennedy"],
  ["Plans are worthless, but planning is everything.", "Dwight D. Eisenhower"],
  ["Honesty is the first chapter in the book of wisdom.", "Thomas Jefferson"],
  ["These are the times that try men's souls.", "Thomas Paine"],
  ["Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", "Martin Luther King Jr."],
  ["If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", "Martin Luther King Jr."],
  ["The time is always right to do what is right.", "Martin Luther King Jr."],
  ["Life's most persistent and urgent question is, 'What are you doing for others?'", "Martin Luther King Jr."],
  ["We must accept finite disappointment, but never lose infinite hope.", "Martin Luther King Jr."],
  ["Never give in, never give in, never, never, never, never.", "Winston Churchill"],
  ["To improve is to change; to be perfect is to change often.", "Winston Churchill"],
  ["This is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning.", "Winston Churchill"],
  ["If there is no struggle, there is no progress.", "Frederick Douglass"],
  ["Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", "Booker T. Washington"],
  ["You must do the thing you think you cannot do.", "Eleanor Roosevelt"],
  ["Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", "Helen Keller"],
  ["Life is either a daring adventure or nothing.", "Helen Keller"],
  ["How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank"],
  ["When we are no longer able to change a situation, we are challenged to change ourselves.", "Viktor Frankl"],
  ["He who has a why to live for can bear with almost any how.", "Nietzsche, as quoted by Viktor Frankl"],
  ["Look for the helpers. You will always find people who are helping.", "Fred Rogers, quoting his mother"],
  ["Life is like riding a bicycle. To keep your balance you must keep moving.", "Albert Einstein"],
  ["Imagination is more important than knowledge.", "Albert Einstein"],
  ["Try not to become a man of success, but rather try to become a man of value.", "Albert Einstein"],
  ["The important thing is not to stop questioning.", "Albert Einstein"],
  ["Genius is one per cent inspiration and ninety-nine per cent perspiration.", "Thomas Edison"],
  ["Failure is simply the opportunity to begin again, this time more intelligently.", "Henry Ford"],
  ["Whether you think you can, or you think you can't, you're right.", "Attributed to Henry Ford"],
  ["If I have seen further it is by standing on the shoulders of Giants.", "Isaac Newton"],
  ["Chance favors only the prepared mind.", "Louis Pasteur"],
  ["The first principle is that you must not fool yourself, and you are the easiest person to fool.", "Richard Feynman"],
  ["That's one small step for a man, one giant leap for mankind.", "Neil Armstrong"],
  ["Give me a place to stand, and I will move the earth.", "Archimedes"],
  ["Never put off till to-morrow what you can do day after to-morrow just as well.", "Mark Twain"],
  ["Courage is resistance to fear, mastery of fear, not absence of fear.", "Mark Twain"],
  ["Always do right. This will gratify some people and astonish the rest.", "Mark Twain"],
  ["Let us endeavor so to live that when we come to die even the undertaker will be sorry.", "Mark Twain"],
  ["If you tell the truth you don't have to remember anything.", "Mark Twain"],
  ["Good friends, good books, and a sleepy conscience: this is the ideal life.", "Mark Twain"],
  ["This above all: to thine own self be true.", "William Shakespeare, Hamlet"],
  ["Our doubts are traitors, and make us lose the good we oft might win by fearing to attempt.", "William Shakespeare, Measure for Measure"],
  ["Some are born great, some achieve greatness, and some have greatness thrust upon 'em.", "William Shakespeare, Twelfth Night"],
  ["There is nothing either good or bad, but thinking makes it so.", "William Shakespeare, Hamlet"],
  ["The fault, dear Brutus, is not in our stars, but in ourselves.", "William Shakespeare, Julius Caesar"],
  ["We know what we are, but know not what we may be.", "William Shakespeare, Hamlet"],
  ["How far that little candle throws his beams! So shines a good deed in a weary world.", "William Shakespeare, The Merchant of Venice"],
  ["Love all, trust a few, do wrong to none.", "William Shakespeare, All's Well That Ends Well"],
  ["There is a tide in the affairs of men, which, taken at the flood, leads on to fortune.", "William Shakespeare, Julius Caesar"],
  ["Wisely and slow; they stumble that run fast.", "William Shakespeare, Romeo and Juliet"],
  ["Though she be but little, she is fierce.", "William Shakespeare, A Midsummer Night's Dream"],
  ["What's past is prologue.", "William Shakespeare, The Tempest"],
  ["Brevity is the soul of wit.", "William Shakespeare, Hamlet"],
  ["Cowards die many times before their deaths; the valiant never taste of death but once.", "William Shakespeare, Julius Caesar"],
  ["Things won are done; joy's soul lies in the doing.", "William Shakespeare, Troilus and Cressida"],
  ["Better three hours too soon than a minute too late.", "William Shakespeare, The Merry Wives of Windsor"],
  ["All the world's a stage, and all the men and women merely players.", "William Shakespeare, As You Like It"],
  ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant, on Aristotle"],
  ["Well begun is half done.", "Greek proverb, quoted by Aristotle"],
  ["One swallow does not make a summer.", "Aristotle"],
  ["The unexamined life is not worth living.", "Socrates"],
  ["The beginning is the most important part of the work.", "Plato"],
  ["Know thyself.", "Inscription at Delphi"],
  ["Nothing in excess.", "Inscription at Delphi"],
  ["No man ever steps in the same river twice.", "Heraclitus"],
  ["Life is short, the art long.", "Hippocrates"],
  ["Seize the day.", "Horace"],
  ["They can because they think they can.", "Virgil"],
  ["Dripping water hollows out stone.", "Ovid"],
  ["While there's life, there's hope.", "Cicero"],
  ["I came, I saw, I conquered.", "Julius Caesar"],
  ["Make haste slowly.", "Augustus"],
  ["Through hardships to the stars.", "Latin motto"],
  ["Fortune favors the bold.", "Latin proverb"],
  ["While we are postponing, life speeds by.", "Seneca"],
  ["It is not that we have a short time to live, but that we waste a lot of it.", "Seneca"],
  ["As is a tale, so is life: not how long it is, but how good it is, is what matters.", "Seneca"],
  ["Men are disturbed not by the things which happen, but by the opinions about the things.", "Epictetus"],
  ["First say to yourself what you would be; and then do what you have to do.", "Epictetus"],
  ["No man is free who is not master of himself.", "Epictetus"],
  ["Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"],
  ["Loss is nothing else than change.", "Marcus Aurelius"],
  ["The superior man is modest in his speech, but exceeds in his actions.", "Confucius"],
  ["When we see men of worth, we should think of equaling them.", "Confucius"],
  ["When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it; this is knowledge.", "Confucius"],
  ["A journey of a thousand miles begins with a single step.", "Laozi (common translation)"],
  ["Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", "Sun Tzu"],
  ["Knowing is not enough; we must apply. Willing is not enough; we must do.", "Johann Wolfgang von Goethe"],
  ["The two most powerful warriors are patience and time.", "Leo Tolstoy"],
  ["Courage is not simply one of the virtues, but the form of every virtue at the testing point.", "C. S. Lewis"],
  ["All we have to decide is what to do with the time that is given us.", "J. R. R. Tolkien"],
  ["Not all those who wander are lost.", "J. R. R. Tolkien"],
  ["Two roads diverged in a wood, and I, I took the one less traveled by, and that has made all the difference.", "Robert Frost"],
  ["The woods are lovely, dark and deep, but I have promises to keep.", "Robert Frost"],
  ["In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"],
  ["I am the master of my fate, I am the captain of my soul.", "William Ernest Henley"],
  ["Lives of great men all remind us we can make our lives sublime.", "Henry Wadsworth Longfellow"],
  ["To strive, to seek, to find, and not to yield.", "Alfred, Lord Tennyson"],
  ["If you can keep your head when all about you are losing theirs...", "Rudyard Kipling"],
  ["Hope is the thing with feathers that perches in the soul.", "Emily Dickinson"],
  ["To err is human; to forgive, divine.", "Alexander Pope"],
  ["Hope springs eternal in the human breast.", "Alexander Pope"],
  ["Life can only be understood backwards; but it must be lived forwards.", "Søren Kierkegaard"],
  ["The perfect is the enemy of the good.", "Voltaire"],
  ["That which does not kill us makes us stronger.", "Friedrich Nietzsche"],
  ["Great works are performed not by strength but by perseverance.", "Samuel Johnson"],
  ["Blessed is he who has found his work; let him ask no other blessedness.", "Thomas Carlyle"],
  ["Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", "Samuel Beckett"],
  ["In the midst of winter, I found there was, within me, an invincible summer.", "Albert Camus"],
  ["It is only with the heart that one can see rightly; what is essential is invisible to the eye.", "Antoine de Saint-Exupéry"],
  ["The world breaks everyone and afterward many are strong at the broken places.", "Ernest Hemingway"],
  ["We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde"],
  ["Those who cannot change their minds cannot change anything.", "George Bernard Shaw"],
  ["Work is love made visible.", "Kahlil Gibran"],
  ["You cannot cross the sea merely by standing and staring at the water.", "Rabindranath Tagore"],
  ["By perseverance the snail reached the ark.", "Charles Spurgeon"],
  ["Hope is a good breakfast, but it is a bad supper.", "Francis Bacon"],
  ["Knowledge is power.", "Francis Bacon"],
  ["The pen is mightier than the sword.", "Edward Bulwer-Lytton"],
  ["It is always darkest just before the day dawneth.", "Thomas Fuller"],
  ["If at first you don't succeed, try, try again.", "William Edward Hickson"],
  ["Life is what happens to you while you're busy making other plans.", "Allen Saunders"],
  ["Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.", "Proverb, popularized by Anne Isabella Ritchie"],
  ["Whatever the mind of man can conceive and believe, it can achieve.", "Napoleon Hill"],
  ["A ship in harbor is safe, but that is not what ships are built for.", "John A. Shedd"],
  ["No act of kindness, no matter how small, is ever wasted.", "Aesop, The Lion and the Mouse"],
  ["Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1.", "Warren Buffett"],
  ["Price is what you pay. Value is what you get.", "Warren Buffett"],
  ["Be fearful when others are greedy and greedy when others are fearful.", "Warren Buffett"],
  ["Stay hungry. Stay foolish.", "Whole Earth Catalog, quoted by Steve Jobs"],
  ["The only way to do great work is to love what you do.", "Steve Jobs"],
  ["You miss 100% of the shots you don't take.", "Wayne Gretzky"],
  ["I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"],
  ["Float like a butterfly, sting like a bee.", "Muhammad Ali"],
  ["Be water, my friend.", "Bruce Lee"],
  ["It ain't over till it's over.", "Yogi Berra"],
  ["When you come to a fork in the road, take it.", "Yogi Berra"],
  ["Be quick, but don't hurry.", "John Wooden"],
  ["Don't let what you cannot do interfere with what you can do.", "John Wooden"],
  ["It's not whether you get knocked down; it's whether you get up.", "Vince Lombardi"],
  ["Perfection is not attainable, but if we chase perfection we can catch excellence.", "Vince Lombardi"],
  ["Don't give up. Don't ever give up.", "Jim Valvano"],
  ["A life is not important except in the impact it has on other lives.", "Jackie Robinson"],
  ["Today I consider myself the luckiest man on the face of the earth.", "Lou Gehrig"],
  ["Don't look back. Something might be gaining on you.", "Satchel Paige"],
  ["We don't make mistakes, just happy little accidents.", "Bob Ross"],
  ["The only real stumbling block is fear of failure. In cooking you've got to have a what-the-hell attitude.", "Julia Child"],
  ["Just do it.", "Nike slogan"],
  ["Do. Or do not. There is no try.", "Yoda, The Empire Strikes Back"],
  ["It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", "Rocky Balboa"],
  ["Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", "Ferris Bueller's Day Off"],
  ["Get busy living, or get busy dying.", "The Shawshank Redemption"],
  ["Carpe diem. Seize the day, boys. Make your lives extraordinary.", "Dead Poets Society"],
  ["Just keep swimming.", "Dory, Finding Nemo"],
  ["If you build it, he will come.", "Field of Dreams"],
  ["It's supposed to be hard. If it wasn't hard, everyone would do it. The hard is what makes it great.", "A League of Their Own"],
  ["Failure is not an option.", "Apollo 13"],
  ["Don't ever let somebody tell you you can't do something.", "The Pursuit of Happyness"],
  ["Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.", "Master Oogway, Kung Fu Panda"],
  ["The past can hurt. But the way I see it, you can either run from it, or learn from it.", "Rafiki, The Lion King"],
  ["It is our choices that show what we truly are, far more than our abilities.", "Albus Dumbledore, Harry Potter"],
  ["My mama always said life was like a box of chocolates. You never know what you're gonna get.", "Forrest Gump"],
  ["To infinity and beyond!", "Buzz Lightyear, Toy Story"],
  ["A merry heart doeth good like a medicine.", "Proverbs 17:22"],
  ["Go to the ant, thou sluggard; consider her ways, and be wise.", "Proverbs 6:6"],
  ["Commit thy works unto the LORD, and thy thoughts shall be established.", "Proverbs 16:3"],
  ["Trust in the LORD with all thine heart; and lean not unto thine own understanding.", "Proverbs 3:5"],
  ["I can do all things through Christ which strengtheneth me.", "Philippians 4:13"],
  ["Be strong and of a good courage; be not afraid, neither be thou dismayed.", "Joshua 1:9"],
  ["This is the day which the LORD hath made; we will rejoice and be glad in it.", "Psalm 118:24"],
  ["His compassions fail not. They are new every morning: great is thy faithfulness.", "Lamentations 3:22–23"],
  ["And whatsoever ye do, do it heartily, as to the Lord, and not unto men.", "Colossians 3:23"],
  ["Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.", "Matthew 6:34"],
  ["Whatsoever thy hand findeth to do, do it with thy might.", "Ecclesiastes 9:10"],
  ["Let us not be weary in well doing: for in due season we shall reap, if we faint not.", "Galatians 6:9"],
  ["Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.", "Proverbs 27:17"],
  ["They shall run, and not be weary; and they shall walk, and not faint.", "Isaiah 40:31"],
  ["Be still, and know that I am God.", "Psalm 46:10"],
  ["A soft answer turneth away wrath.", "Proverbs 15:1"],
  ["Rejoicing in hope; patient in tribulation; continuing instant in prayer.", "Romans 12:12"],
  ["Do justly, and to love mercy, and to walk humbly with thy God.", "Micah 6:8"],
  ["Seest thou a man diligent in his business? he shall stand before kings.", "Proverbs 22:29"],
  ["He that gathereth by labour shall increase.", "Proverbs 13:11"],
  ["Where there is no vision, the people perish.", "Proverbs 29:18"],
  ["Weeping may endure for a night, but joy cometh in the morning.", "Psalm 30:5"],
  ["To every thing there is a season, and a time to every purpose under the heaven.", "Ecclesiastes 3:1"],
  ["Keep thy heart with all diligence; for out of it are the issues of life.", "Proverbs 4:23"],
  ["For a just man falleth seven times, and riseth up again.", "Proverbs 24:16"],
  ["Ye are the light of the world.", "Matthew 5:14"],
  ["For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", "2 Timothy 1:7"],
  ["A man's heart deviseth his way: but the LORD directeth his steps.", "Proverbs 16:9"],
  ["Let every man be swift to hear, slow to speak, slow to wrath.", "James 1:19"],
  ["Now faith is the substance of things hoped for, the evidence of things not seen.", "Hebrews 11:1"],
  ["Even if the sky falls, there is a hole to rise up through.", "Korean proverb"],
  ["Even a journey of a thousand li begins with a single step.", "Korean proverb"],
  ["Raindrops falling from the eaves will bore through the stone step.", "Korean proverb"],
  ["Even monkeys fall from trees.", "Korean proverb"],
  ["If the words you send are kind, the words that come back will be kind.", "Korean proverb"],
  ["Starting is half the work.", "Korean proverb"],
  ["Gather enough specks of dust and you have a great mountain.", "Korean proverb"],
  ["At the end of hardship, joy arrives.", "Korean proverb"],
  ["Even if a tiger drags you into its den, keep your wits about you and you will survive.", "Korean proverb"],
  ["There is no tree that won't fall after ten swings of the axe.", "Korean proverb"],
  ["Tap even a stone bridge before you cross it.", "Korean proverb"],
  ["The riper the rice, the lower it bows its head.", "Korean proverb"],
  ["The ground hardens after the rain.", "Korean proverb"],
  ["Even a mouse hole gets sunlight someday.", "Korean proverb"],
  ["When ten people each give a spoonful, it makes a bowl of rice.", "Korean proverb"],
  ["Fall seven times, stand up eight.", "Japanese proverb"],
  ["The morning hour has gold in its mouth.", "German proverb"],
  ["May the road rise up to meet you. May the wind be always at your back.", "Irish blessing"],
  ["Where there's a will, there's a way.", "Proverb"],
  ["Practice makes perfect.", "Proverb"],
  ["Actions speak louder than words.", "Proverb"],
  ["The early bird catches the worm.", "Proverb"],
  ["A smooth sea never made a skilled sailor.", "Proverb"],
  ["Every cloud has a silver lining.", "Proverb"],
  ["Make hay while the sun shines.", "Proverb"],
  ["Rome wasn't built in a day.", "Proverb"],
  ["Slow and steady wins the race.", "Proverb"],
  ["Necessity is the mother of invention.", "Proverb"],
  ["Two heads are better than one.", "Proverb"],
  ["Better late than never.", "Proverb"],
  ["Patience is a virtue.", "Proverb"],
  ["Strike while the iron is hot.", "Proverb"],
  ["A rolling stone gathers no moss.", "Proverb"],
  ["Honesty is the best policy.", "Proverb"],
  ["Laughter is the best medicine.", "Proverb"],
  ["United we stand, divided we fall.", "Proverb"],
  ["A friend in need is a friend indeed.", "Proverb"],
  ["Tomorrow is another day.", "Proverb"],
  ["Hope for the best, prepare for the worst.", "Proverb"],
  ["Nothing ventured, nothing gained.", "Proverb"],
  ["Measure twice, cut once.", "Proverb"]
];

window.DAILY_JOKES = [
  "I'm reading a book about anti-gravity. It's impossible to put down.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "What do you call a fake noodle? An impasta.",
  "I used to hate facial hair, but then it grew on me.",
  "Why can't you trust atoms? They make up everything.",
  "How do you organize a space party? You planet.",
  "Why did the bicycle fall over? It was two-tired.",
  "Parallel lines have so much in common. Shame they'll never meet.",
  "I'm on a seafood diet. I see food, and I eat it.",
  "I tried to catch some fog this morning. I mist.",
  "I used to be a banker, but I lost interest.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "Why did the math book look sad? It had too many problems.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why can't a leopard play hide and seek? He's always spotted.",
  "I'm worried about the calendar. Its days are numbered.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "Why do seagulls fly over the sea? If they flew over the bay, they'd be bagels.",
  "How does a penguin build its house? Igloos it together.",
  "What do you call a fish with no eyes? A fsh.",
  "Why did the coffee file a police report? It got mugged.",
  "What do you call a pile of cats? A meowntain.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What's orange and sounds like a parrot? A carrot.",
  "Want to hear a joke about construction? I'm still working on it.",
  "Why don't scientists trust stairs? They're always up to something.",
  "I used to play piano by ear. Now I use my hands.",
  "Did you hear about the claustrophobic astronaut? He just needed a little space.",
  "What's brown and sticky? A stick.",
  "Why did the tomato blush? It saw the salad dressing.",
  "What do you call a dinosaur that crashes his car? Tyrannosaurus wrecks.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why can't a nose be 12 inches long? Then it would be a foot.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "Why do cows wear bells? Because their horns don't work.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why did the picture go to jail? It was framed.",
  "What kind of shoes do ninjas wear? Sneakers.",
  "What did the zero say to the eight? Nice belt.",
  "Why don't oysters donate to charity? Because they're shellfish.",
  "Why did the cookie go to the doctor? It was feeling crumby.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you call a can opener that doesn't work? A can't opener.",
  "Why did the banana go to the doctor? It wasn't peeling well.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "What did the grape do when it got stepped on? It let out a little wine.",
  "Elevator jokes are great. They work on so many levels.",
  "Why did the invisible man turn down the job? He couldn't see himself doing it.",
  "What do you call an alligator in a vest? An investigator.",
  "I'm afraid of elevators, so I'm taking steps to avoid them.",
  "What do you call a man with a rubber toe? Roberto.",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
  "What do you call a deer with no eyes? No idea.",
  "Why did the stadium get hot after the game? All the fans left.",
  "Why did the man fall down the well? He couldn't see that well.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "I asked my dog what two minus two is. He said nothing.",
  "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
  "What do you call a belt made of watches? A waist of time.",
  "What did the buffalo say when his son left for college? Bison.",
  "What's an astronaut's favorite key on the keyboard? The space bar.",
  "What did the pirate say on his 80th birthday? Aye matey.",
  "Why are ghosts bad liars? You can see right through them.",
  "What do you call a fake stone in Ireland? A sham rock.",
  "How does the moon cut his hair? Eclipse it.",
  "What kind of tree fits in your hand? A palm tree.",
  "Why did the orange stop halfway up the hill? It ran out of juice.",
  "What do you call a lazy kangaroo? A pouch potato.",
  "Why did the cow go to outer space? To see the moooon.",
  "Why do melons have fancy weddings? Because they cantaloupe.",
  "What did one hat say to the other? Stay here, I'm going on ahead.",
  "What do you call a boomerang that won't come back? A stick.",
  "What do you call a duck that gets all A's? A wise quacker.",
  "I got hit in the head with a can of soda. Luckily, it was a soft drink.",
  "What did the drummer name his twin daughters? Anna One and Anna Two.",
  "Why did the cow cross the road? To get to the udder side.",
  "What did the fish say when it swam into a wall? Dam.",
  "What does a cloud wear under its raincoat? Thunderwear.",
  "Why did the sun go to school? To get a little brighter.",
  "What do you call a pig that does karate? A pork chop.",
  "Why was six afraid of seven? Because seven eight nine.",
  "What did the traffic light say to the car? Don't look, I'm changing.",
  "How does a cucumber become a pickle? It goes through a jarring experience.",
  "What's a skeleton's least favorite room? The living room.",
  "What did the big flower say to the little flower? Hi, bud!",
  "I used to be addicted to the hokey pokey, but I turned myself around.",
  "What did the hot dog say when it won the race? I'm the wiener!",
  "What do you call a magic dog? A labracadabrador.",
  "Why did the music teacher need a ladder? To reach the high notes.",
  "Where do boats go when they're sick? To the dock.",
  "Why was the belt arrested? It was holding up a pair of pants.",
  "Why did the frog take the bus to work? His car got toad.",
  "What's a computer's favorite snack? Microchips.",
  "Why don't mountains get cold? They wear snowcaps.",
  "What do you call a cow with no legs? Ground beef.",
  "What do you call a cow during an earthquake? A milkshake.",
  "Why did the tree go to the dentist? It needed a root canal.",
  "What kind of music do planets like? Neptunes.",
  "Why are fish so smart? They live in schools.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Why did the student eat his homework? The teacher said it was a piece of cake.",
  "Why did the chicken join a band? It already had the drumsticks.",
  "I told my weather app a joke. It gave me a 60% chance of laughter.",
  "I'd tell you a joke about fog, but it's not very clear.",
  "My alarm clock and I have an agreement: it goes off, and I don't.",
  "The thermometer broke up with the barometer. Too much pressure.",
  "Delivery windows are like weather forecasts: technically accurate, emotionally unhelpful.",
  "My phone battery and I have the same morning: start at 100%, drop fast.",
  "Sunscreen is just you telling the sun, “Not today.”",
  "The forecast said 0% chance of rain. My freshly washed car disagreed.",
  "I asked the sun how it stays so positive. It said, “I just keep rising.”",
  "My coffee and I have a lot in common. We both work better under pressure. Mostly the coffee.",
  "Why did the cloud stay home? It was feeling a little under the weather.",
  "My cat treats the sunny spot on the floor like a reservation, not a coincidence.",
  "What's a tornado's favorite game? Twister.",
  "How do hurricanes see? With one eye.",
  "What did the lightning bolt say to the other lightning bolt? You're shocking!",
  "Why did the weather forecaster bring a bar of soap to work? She was predicting showers.",
  "What do you call it when it rains chickens and ducks? Fowl weather.",
  "Why did the snowman call his dog Frost? Because Frost bites.",
  "What's the best day to go to the beach? Sunday, of course.",
  "Why did the computer catch a cold? It left its Windows open."
];

window.DAILY_JOKES_KOREAN = [
  "Korean moms have one weather forecast: “Wear a jacket.”",
  "Korean dads know two kinds of weather: “nice” and “you should've worn a jacket.”",
  "My Korean mom doesn't say “I love you.” She asks “Did you eat?” and then feeds me until I can't move.",
  "Korean mom logic: “You're not hungry? You must be sick. Eat.”",
  "Korean mom on the phone: “Did you eat?” “Yes.” “What did you eat?” “Food.” “Eat more.”",
  "Korean moms don't text “I love you.” They bring you a plate of cut fruit.",
  "Cut fruit on a plate at 10 PM is the Korean way of saying “I'm sorry we argued.”",
  "Korean dads don't say “I'm proud of you.” They tell their friends, loudly, while you're in the next room.",
  "Korean parents' praise scale: “Not bad” means “I'm incredibly proud of you.”",
  "Korean dad jokes are called “ajae gags.” Congratulations, you're reading one.",
  "“Aigoo” is the sound every Korean makes when standing up after age 30.",
  "“Aigoo” can mean oh no, oh my, I'm tired, you're cute, and I'm disappointed in you. Context is everything.",
  "Korean grandmas don't use recipes. “Just a little” and “enough” are precise measurements.",
  "Son-mat: the secret ingredient in Korean food that only works if your mom's hands made it.",
  "Halmeoni's three answers to every problem: eat something, sleep early, wear warm socks.",
  "Korean grandmas are the best weather forecasters. Their knees know it's going to rain before the news does.",
  "My halmeoni can tell how cold it is outside just by looking at my outfit. The answer is always “too cold.”",
  "Korean grandmas believe a cold drink will ruin your stomach. Even in August.",
  "Korean moms aren't afraid of summer heat. They're afraid of a fan running with the door closed.",
  "Why do Korean moms pack so much food for a trip? In case it lasts longer than planned. It's a day trip.",
  "Every Korean family photo has one person blinking and one person saying “One more!”",
  "Every Korean household has a blue butter cookie tin. None of them contain cookies.",
  "A Korean refrigerator has two kinds of containers: kimchi, and containers that used to hold something else and now hold kimchi.",
  "Kimchi fridges exist because regular fridges couldn't handle the commitment.",
  "Kimchi is proof that some things get better with age. My knees are proof that not everything does.",
  "Kimchi never panics. It just takes time to process.",
  "Kimchi jjigae is what happens when kimchi gets too sour to eat, so it gets promoted to soup.",
  "Kimjang day: the whole family makes 200 heads of kimchi and nobody can feel their hands.",
  "What did the rice say to the bibimbap? “Let's mix it up.”",
  "Bibimbap: every food on the table, one bowl, zero decisions.",
  "What do you call a dumpling that gets things done? Man-du.",
  "What's a Korean ghost's favorite food? Boo-lgogi.",
  "What did the gochujang say to the bland soup? “Don't worry, I've got this.”",
  "Gochugaru: the red powder that turns any meal into a personality test.",
  "My spice tolerance is “mild.” My grandma's definition of mild is “only one pepper.”",
  "Korean food rule: if it's not spicy, it's a side dish. If it is spicy, it's also a side dish.",
  "Banchan showed up with eleven friends and nobody ordered any of them. Best party crashers ever.",
  "Free banchan refills: the Korean version of an endless love story.",
  "Korean BBQ is the only meal where you pay to cook your own food and still leave happy.",
  "Korean BBQ rule: whoever holds the tongs is in charge. Respect the tongs.",
  "Samgyeopsal: three layers of pork belly, three layers of happiness, three days of smelling like it.",
  "Leave Korean BBQ and you'll smell like samgyeopsal for two days. Best cologne in the world.",
  "The correct size for a lettuce wrap: slightly too big to fit in your mouth.",
  "The lettuce wrap felt overwhelmed. Everyone stuffed it with meat, rice, garlic, and ssamjang at once.",
  "Ramyeon tastes best when someone else made it and you only asked for “just one bite.”",
  "The most dangerous words in Korea: “I'll just have one bite of your ramyeon.”",
  "Kimbap is just a burrito that went to a very good school.",
  "Why was the kimbap so organized? Everything was rolled into place.",
  "Why do tteokbokki never get lonely? They always bring the fish cakes.",
  "Hotteok is proof that winter can be delicious.",
  "Bungeoppang: a fish that tastes like red beans. Korea's most delicious lie.",
  "Dalgona: the only candy that comes with a stress test.",
  "Banana milk tastes better from that little round jar. That's just science.",
  "Korean pears are so big they come with their own foam jacket. They're better dressed for winter than I am.",
  "Seoul food: food that's good for the soul. And the soul is hungry again in an hour.",
  "Why is Seoul so good for relationships? Everyone's looking for their Seoul-mate.",
  "Jjajangmyeon or jjamppong? The hardest decision in Korea. That's why the half-and-half bowl was invented.",
  "Moving day in Korea isn't official until someone orders jjajangmyeon.",
  "Black Day: April 14, when singles in Korea eat jjajangmyeon together. Even being single has a menu.",
  "Pepero Day: the holiday where you exchange chocolate sticks and pretend it isn't just a snack sale.",
  "White Day: the sequel to Valentine's Day. Like a good K-drama, it always gets a second season.",
  "Korean couples celebrate their 100-day anniversary. My houseplants don't even make it to day 30.",
  "Chimaek: chicken and beer. The two-word Korean recipe for a perfect evening.",
  "Korean fried chicken is fried twice. My diet has been ruined twice.",
  "In Korea, you can get fried chicken delivered to a picnic blanket by the Han River.",
  "Korean delivery is so fast the food arrives before you finish deciding what to order.",
  "“Ppalli ppalli” isn't a phrase. It's a lifestyle.",
  "In every Korean elevator, the “close door” button is the most worn-out button.",
  "Korean restaurants put a call bell on every table, because saying “excuse me” takes too long.",
  "Korean convenience stores have everything. I went in for milk and came out with dinner, a phone charger, and a new hobby.",
  "1+1 deals at Korean convenience stores: the only math I've ever enjoyed.",
  "Korean umbrella rule: when it rains, buy another one at the convenience store. You now own 47 umbrellas.",
  "Rainy day in Korea means pajeon and makgeolli. The sound of rain and sizzling oil are basically the same.",
  "Korean summer logic: it's 95 degrees, so let's eat boiling samgyetang. Fight fire with fire.",
  "Hot Korean soup makes you say “siwonhada”: refreshing. Korean logic: boiling is refreshing.",
  "Naengmyeon: noodles so cold they come with ice. The air conditioning of food.",
  "Patbingsu is so good it should count as a weather event.",
  "Monsoon season in Korea: your hair, your laundry, and your patience are all equally damp.",
  "Yellow dust season: when Koreans check the air quality before they check the weather.",
  "Korean winter coats go down to the ankles. Basically sleeping bags with legs.",
  "Ondol floor heating is why Koreans sleep on the floor. It's not a bed shortage. It's a warmth strategy.",
  "Korean homes have slippers just for the bathroom. The bathroom has a dress code.",
  "Taking your shoes off in a Korean home is really a test of whether your socks match.",
  "Korean buildings label the 4th floor “F.” Even the elevator is superstitious.",
  "Korean superstition: shaking your leg shakes your luck away. I've been very unlucky all week.",
  "Whistling at night in Korea supposedly invites snakes. That's why I hum.",
  "Dream about a pig, buy a lottery ticket. Korean financial planning at its finest.",
  "Don't give your partner shoes in Korea. Supposedly they'll walk away. Socks are the safe gift.",
  "Make pretty songpyeon on Chuseok and you'll have pretty kids someday. No pressure.",
  "Seaweed soup on your birthday: Korea's way of saying “Happy birthday, now go thank your mom.”",
  "Sebae on New Year's: the only workout that pays in cash.",
  "Eating tteokguk on New Year's makes you a year older. I'm stopping at one bowl.",
  "Korean age used to make you one year old the day you were born. Happy birthday, here's a free year.",
  "Korea switched to international age in 2023. Overnight, a whole country got younger. Best anti-aging product ever.",
  "Respect in Korea is based on age, so every first meeting starts with a little math.",
  "In Korea, “What year were you born?” isn't small talk. It decides who uses honorifics.",
  "Korean group dinner rule: the oldest person pays. Suddenly everyone wants to be the youngest.",
  "“Let's get a meal sometime” is the most beautiful promise in Korean. Nobody plans to keep it.",
  "I pour my morning coffee with two hands, Korean-style. It's 6 AM and I need the support.",
  "Korean drama rule #1: if a truck appears, someone's about to get amnesia.",
  "In K-dramas, nobody falls in love until someone grabs a wrist in slow motion.",
  "K-drama characters never need a weather app. It only rains when someone's heart is broken.",
  "In K-dramas, holding an umbrella over someone's head counts as a love confession.",
  "K-drama piggyback rides: the official transportation of people who had too much soju.",
  "In K-dramas, the second lead always has the better personality and the worse luck.",
  "You know a K-drama is getting serious when the rich mom offers an envelope of money.",
  "My K-drama schedule: “just one more episode” until the sun comes up.",
  "Noraebang rule: whoever said “I don't sing” will not give up the mic.",
  "K-pop dance practice: perfectly synchronized. My family trying to leave the house: not so much.",
  "K-pop concerts are so bright with lightsticks that the sun gets jealous.",
  "Jjimjilbang: where you pay to sit in an oven and call it relaxing.",
  "A Korean dad doesn't go to the doctor. He goes to the jjimjilbang and sweats it out.",
  "Korean hikers dress like they're summiting Everest. It's a one-hour trail.",
  "Korean hiking rule: the hike is just the warm-up for the makgeolli and pajeon at the bottom.",
  "Korean cafes have more floors than some office buildings, and better Wi-Fi.",
  "A PC bang is a gym for your thumbs, with ramyeon delivered to your seat.",
  "Hagwon: where Korean kids go after school to go to school.",
  "Jindo dogs are so loyal they'd put it on their resume.",
  "My rice cooker talks to me in polite Korean. It's the most respectful conversation I'll have all day.",
  "“Hwaiting!” is Korean for “you've got this.” Today's forecast: 100% chance of hwaiting.",
  "“Daebak”: what you say when it's amazing. Also when it's a disaster. Also when the food arrives.",
  "My Korean vocabulary is mostly food words and “saranghae.” Somehow that covers most situations.",
  "Banmal versus jondaemal: the difference between “hey” and “respected elder, may I please have a snack.”",
  "Nunchi: the Korean superpower of reading the room. Mine only works when snacks are involved.",
  "Why did the soju stay calm at the party? It was used to being chilled."
];
